- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print loops
    ansible.builtin.debug:
      msg: "Hello, {{ item }}" # her eitem is reserved keyword
    loop:
    - Suresh
    - Ramesh
    - Raheem
    - Joseph