- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}" 

  - name: print names
    ansible.builtin.debug:
      msg: "Hello: {{ persons | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10Hr
        tainer: siva
    ansible.builtin.debug:
      msg: "Course information: {{ course | dict2items }}"

  - name: convert map into list
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10Hr'}
      - {'key': 'tainer', 'value': 'siva'}  
    ansible.builtin.debug:
      msg: "Course information: {{ course | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "Daram Sharmila"
    ansible.builtin.debug:
      msg: "Hello: {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "Daram Sharmila"
    ansible.builtin.debug:
      msg: "Hello: {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "172.138.31.12"
    ansible.builtin.debug:
      msg: " IP is: {{ ip | ansible.utils.ipaddr }}"